### ISSUE TITLE
Expand to UCLA open source projects

### ISSUE THREAD

**Issue by ArshMalik02** [uclaacm/opensource#156]
## Aim

This project was built with the idea of expanding to all UCLA open-source projects, not just those maintained by ACM at UCLA. This issue details the tasks we need to complete in order to reach this milestone.

## Tasks

- [x] Project's Page changes
    - [x] Currently, open-source's [projects page](https://opensource.uclaacm.com/projects) lists all public repositories in the ACM organization. Modify the projects page to list repositories that have `ucla-opensource` added to their list of topics. For reference, here is the [list of current repositories](https://github.com/topics/ucla-opensource) that meet this requirement.
    - [x] Change the description to something appropriate.
- [x] Landing Page changes
    - [x] Change the title to "open source at UCLA", sub-heading "maintained by ACM at UCLA, the largest computer science community at UCLA"
    - [x] Project's page card link: change the description to "check out current UCLA open source projects"
- [x] Contribute Page changes
    - [x] The good first issues list should contain issues from all `ucla-opensource` repositories, not just those maintained by ACM at UCLA.
- [x] Navigation Bar Changes
    - [x] The navigation bar should be more consistent with the main website as opensource is linked on there. This task would essentially require changing the logo in the navbar to be the same one as the main website and linking it back to the main website. We don't need to copy over the entire navbar from the main website.
    - [x] The navigation bar is a bit unresponsive. The buttons get squashed to outside the navigation bar on reducing the window width. This would be resolved by recreating the hamburger menu that has been implemented on the UCLA ACM main website.

**Comment by ArshMalik02** [comment]
@AudreyW05 you can continue working on the rest of the tasks. Assigned the issue to you.
